### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by qdesp** [AkashKarnatak/chatgpt-anywhere#2]
C:\chatgpt-anywhere>npm run build

> chatgpt-anywhere@1.0.0 build
> npm run bundle && npm run postBundle

> chatgpt-anywhere@1.0.0 bundle
> browserify ./src/background.js --standalone bundle -o ./extension/background.js

Error: Can't walk dependency graph: Cannot find module '@microsoft/fetch-event-source' from 'C:\chatgpt-anywhere\src\background.js'
    required by C:\chatgpt-anywhere\src\background.js
    at C:\chatgpt-anywhere\node_modules\resolve\lib\async.js:146:35
    at processDirs (C:\chatgpt-anywhere\node_modules\resolve\lib\async.js:299:39)
    at isdir (C:\chatgpt-anywhere\node_modules\resolve\lib\async.js:306:32)
    at C:\chatgpt-anywhere\node_modules\resolve\lib\async.js:34:69
    at FSReqCallback.oncomplete (node:fs:201:21)

**Comment by AkashKarnatak** [comment]
I have updated my fork of `@microsoft/fetch-event-source` to include lib files in the git repo, as I directly install from github. This issue has now been fixed.
