### ISSUE TITLE
ChatGPT Browser Documentation.

### ISSUE THREAD

**Issue by TheRealJamesRussell** [AkashKarnatak/chatgpt-anywhere#3]
Hey, I'm working on a project and looking for ways to import external data into ChatGPT in the browser. 

Is there any documentation on how to achieve it?

**Comment by AkashKarnatak** [comment]
Chatgpt browser api documentation doesn't exist.

**Comment by TheRealJamesRussell** [comment]
Could you point me in the right direction? I would love to understand how to do this for myself.

**Comment by AkashKarnatak** [comment]
I am not sure what you are trying to achieve. Can you elaborate on your problem?

**Comment by TheRealJamesRussell** [comment]
I'm working on a prompt base for me and a bud. 

Features are currently supporting prompts with variables. prompts going directly to OpenAI's api.

We both have ChatGPT Pro accounts and would prefer to go from promptbase directly to chatgpt.

I want to learn how to use the API you use to talk directly to ChatGPT and use gpt for free.

**Comment by AkashKarnatak** [comment]
I am using the API endpoint that openai uses for chatgpt in the browser. This endpoint requires an authorisation token that you can get by hitting the `auth/session` endpoint. You can read the `src/background.js` file to understand how I am calling those endpoints.

**Comment by TheRealJamesRussell** [comment]
Thanks!
