### ISSUE TITLE
npm run build doesn't create valid chrome extension.

### ISSUE THREAD

**Issue by TheRealJamesRussell** [AkashKarnatak/chatgpt-anywhere#6]
After running npm run build the chrome-extension file, when loaded into chrome says there's no valid manifest file.

I looked into what up:
![image](https://github.com/AkashKarnatak/chatgpt-anywhere/assets/145216038/0f83aa94-e77a-4c25-a0fc-ed242bd3c78d)

Seems like it names it weirdly (and includes the firefox manifest?)

Anyways, I renamed to just "manifest.json" and deleted firefox. that fixed it.

**Comment by James-blend** [comment]
![image](https://github.com/AkashKarnatak/chatgpt-anywhere/assets/145216038/c129496c-a598-44f7-a3db-e228ad7b2179)

**Comment by TheRealJamesRussell** [comment]
I see you added into the package.json to rename the file just to manifest.json but it doesn't seem to do that.

**Comment by AkashKarnatak** [comment]
When you run `npm run build`, a new folder called `chrome-extension` will be created. You have to load the extension from chrome-extension folder instead of extension folder.

**Comment by TheRealJamesRussell** [comment]
The screenshot above is from the chrome extension file.

**Comment by AkashKarnatak** [comment]
Seems like `*` wildcard character doesn't work as intended on windows. I'll look into it and get back to you.

**Comment by AkashKarnatak** [comment]
ed852f4d6fd30b5cf8dd1640663562cfb78ba462 fixes the issue

**Comment by James-blend** [comment]
with the new changes i get this messages:

'browserify' is not recognized as an internal or external command,
operable program or batch file.
